authentication:
  obfuscation: # optional
    key: replaceme
credentials:
  useKeyPairAuth: false
  account: replaceme
  user: replaceme
  password: replaceme
  role: replaceme
  warehouse: replaceme
  privateKey: replaceme
